name: build

on:
  pull_request:

permissions: write-all

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
    
      - name: Set short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
 
      - name: Build
        run: |
          bun install -g npm-run-all
          bun run build

      - uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: ./dist
          destination-dir: ${{ env.SHORT_SHA }}/

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Success!!!
          comment_tag: execution